version: '3'
services:
  base: &base
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
  web:
    <<: *base
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack
    ports:
      - 3000:3000
    depends_on:
      - webpack

  webpack:
    <<: *base
    command: ./bin/webpack-dev-server
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    ports:
      - 3035:3035

volumes:
  node_modules:


