version: '3'
services:
  base: &base
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
  web:
    <<: *base
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack
    ports:
      - 3000:3000
    depends_on:
      - webpack
      - db
  webpack:
    <<: *base
    command: ./bin/webpack-dev-server
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    ports:
      - 3035:3035
  db:
    image: mysql:8.0.21
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password

volumes:
  node_modules:


