version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && foreman start -f Procfile.dev"
    volumes:
      - .:/app
    ports:
      - 3000:3000

