version: '3'
services:
  base: &base
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/rails-app
      - /rails-app/node_modules
  web:
    <<: *base
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack
    ports:
      - 3000:3000
    depends_on:
      - webpack
      - db
      - redis
  webpack:
    <<: *base
    command: ./bin/webpack-dev-server
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    ports:
      - 3035:3035
  db:
    image: mysql:8.0.21
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
  redis:
    image: redis:alpine
    command: [ "sh", "-c", "redis-server" ]
    volumes:
      - redis:/data/redis
    ports:
      - '6380:6379'
volumes:
  mysql-data:
  redis:

